# Variables used in all manifest
[vars]
branch = "sisyphus"


[workers."bb-{{item}}"]
# Create two workers bb-master and bb-worker
items = ["master", "worker"]
[workers."bb-{{item}}".engine.podman]
image = "alt:{{ branch }}"
# Run all containers in the same pod to share network
pod = "lineup-bb"


[[tasklines.setup-master]]
run-taskline = { module = "apt-get", taskline = "install" }
vars.packages = ["buildbot"]

[[tasklines.setup-master]]
shell.command = "buildbot create-master master"

[[tasklines.setup-master]]
shell.command = "mv master/master.cfg.sample master/master.cfg"

[[tasklines.setup-master]]
shell.command = "buildbot restart master"


[[tasklines.setup-worker]]
run-taskline = { module = "apt-get", taskline = "install" }
vars.packages = ["buildbot-worker"]

[[tasklines.setup-worker]]
shell.command = """\
buildbot-worker create-worker worker localhost example-worker pass\
"""

[[tasklines.setup-worker]]
shell.command = "buildbot-worker restart worker"


[taskset.setup-master]
run-taskline = { taskline = "setup-master" }
# Use list of regexes to limit workers to run task, [.*] is default
workers = ["bb-master"]

[taskset.setup-worker]
# Tasks in taskset run independently, requires used to create some order
requires = ["setup-master"]
run-taskline = { taskline = "setup-worker" }
workers = ["bb-worker"]
