# Set default log level
log-level = "Info"

# Control installation of embedded modules
install-embedded-modules = true

# Clean workers after successefully run all tasks
clean = true


# Defaults for tasks
[task]

# Command tasks: common parameters for shell, exec and test tasks
[task.command]
check = true
stdout = { log = "Trace", print = false }
stderr = { log = "Warn", print = false }


# Control errors
[error]
backtrace = true
context = true
context-lines = 10


# Init profiles
[init.profiles.default]
manifest = """\
[workers.{{ engine }}-worker.engine.{{ engine }}]

{% for cmd in commands %}
[[tasklines.{{ task }}]]
shell.cmd = "{{ cmd }}"
shell.stdout.print = {{ print }}
{% endfor %}

[taskset.{{ task }}]
run = "{{ task }}"
"""
render = true
vars.engine = "host"
vars.task = "test"
vars.print = "true"
vars.commands = [
    "echo Hi!"
]
