[[tasklines.add]]
ensure.vars = ["task"]

[[tasklines.add]]
name = "Add task {{ task }}"
exec.args = ["apt-repo", "add", "{{ task }}"]


[[tasklines.rm]]
ensure.vars = ["task"]

[[tasklines.rm]]
name = "Remove task {{ task }}"
exec.args = ["apt-repo", "rm", "{{ task }}"]


[[tasklines.clean]]
name = "Remove all tasks"
exec.args = ["apt-repo", "clean"]
