[vars]
update = true


[[tasklines.update]]
name = "Update packages cache"
shell.command = "apt-get update"


[[tasklines.dist-upgrade]]
run-taskline = { taskline = "update" }
if = "{{ update }}"

[[tasklines.dist-upgrade]]
name = "Upgrade system"
shell.command = "apt-get dist-upgrade -y"


[[tasklines.install]]
ensure.vars = ["packages"]

[[tasklines.install]]
run-taskline = { taskline = "update" }
if = "{{ update }}"

[[tasklines.install]]
name = "Install packages {{ packages }}"
shell.command = "apt-get install -y {{ packages | quote }}"


[[tasklines.reinstall]]
ensure.vars = ["packages"]

[[tasklines.reinstall]]
run-taskline = { taskline = "update" }
if = "{{ update }}"

[[tasklines.reinstall]]
name = "Reinstall packages {{ packages }}"
shell.command = "apt-get reinstall -y {{ packages | quote }}"


[[tasklines.remove]]
ensure.vars = ["packages"]

[[tasklines.remove]]
name = "Remove packages {{ packages }}"
shell.command = "apt-get remove -y {{ packages | quote }}"
