[[taskline]]
name = "Sed file {{ file }} with expression {{ expression }}"
exec.args = ["sed", "-E", "-e", "{{ expression }}", "-i", "{{ file }}"]

[[taskline]]
name = "Run validate command `{{ validate }}`"
shell.command = "{{ validate }}"
if = "{{ validate is defined }}"
