[vars]
now = true


[[tasklines.enable]]
ensure.vars = [
    "services: array | string",

    "now: bool",
]

[[tasklines.enable]]
name = "Enable services {{ services }}"
shell.command = "systemctl enable {{ now | cond(if='--now') }} {{ services | quote }}"


[[tasklines.disable]]
ensure.vars = [
    "services: array | string",

    "now: bool",
]

[[tasklines.disable]]
name = "Disable services {{ services }}"
shell.command = "systemctl disable {{ now | cond(if='--now') }} {{ services | quote }}"


[[tasklines.start]]
ensure.vars = ["services: array | string"]

[[tasklines.start]]
name = "Start services {{ services }}"
shell.command = "systemctl start {{ services | quote }}"


[[tasklines.stop]]
ensure.vars = ["services: array | string"]

[[tasklines.stop]]
name = "Disable services {{ services }}"
shell.command = "systemctl stop {{ services | quote }}"
