[vars]
now = true


[[tasklines.enable]]
name = "Enable services {{ services }}"
shell.command = "systemctl enable {{ now | cond(if='--now') }} {{ services | quote }}"


[[tasklines.disable]]
name = "Disable services {{ services }}"
shell.command = "systemctl disable {{ now | cond(if='--now') }} {{ services | quote }}"


[[tasklines.start]]
name = "Start services {{ services }}"
shell.command = "systemctl start {{ services | quote }}"


[[tasklines.stop]]
name = "Disable services {{ services }}"
shell.command = "systemctl stop {{ services | quote }}"
