[vars]
copy_root_key = true
groups = []
flags = []


[[tasklines._create-ssh-dir]]
shell.command = "mkdir -p ~{{ user }}/.ssh"

[[tasklines._create-ssh-dir]]
shell.command = "chown {{ user }}:{{ user }} ~{{ user }}/.ssh"

[[tasklines._create-ssh-dir]]
shell.command = "chmod 0700 ~{{ user }}/.ssh"


[[tasklines._copy-root-key]]
run-taskline = { taskline = "_create-ssh-dir" }
if = "! [ -d ~{{ user }}/.ssh ]"

[[tasklines._copy-root-key]]
shell.command = "cat ~root/.ssh/authorized_keys >> ~{{ user }}/.ssh/authorized_keys"


[[taskline]]
ensure.vars = [
    "user: string",

    "groups: array | string",
    "flags: array | string",
    "copy_root_key: bool",
]

[[taskline]]
name = "Add user \"{{ user }}\""
shell.cmd = "useradd {{ flags | quote }} {{ user | quote }}"
vars = [
    { gstr = "{{ groups | quote(sep=',') }}" },
    { "j % gflags: a" = "{{ groups | is_empty | cond(if=[], else=['-G', gstr]) | j }}" },
    { "j % flags: a" = "{{ gflags | concat(with='-m') | concat(with=flags) | j }}" },
]
if = "! id {{ user }} 2>/dev/null"

[[taskline]]
name = "Copy root authorized_keys to user {{ user }}"
run-taskline = { taskline = "_copy-root-key" }
if = "{{ copy_root_key }}"
